#For now give up with CI. Run tests manually. Configure Travis later, after main functionality is served.
sudo: required
language: java
jdk:
  - oraclejdk8
services:
  - postgresql
before_script:
  - psql -c "CREATE ROLE $POSTGRES_USER WITH CREATEDB LOGIN PASSWORD '$POSTGRES_PASSWORD';" --username=postgres
  - psql -c "CREATE DATABASE \"$POSTGRES_DB\";" --username=$
addons:
  postgresql: "9.5"